feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

client:
  user-ms:
    name: user-ms
    host: ${USER_MS_HOST:http://localhost:8080}
    path: /user-ms
